stages:
  - build

job:
  stage: build
  script:
    - npm set registry https://registry.npm.taobao.org
    - npm install
    - npm run build:t241
  only:
    - feature_08_29_invoice
  tags:
    - oa
